[package]
authors = ["lholznagel <lars.holznagel@outlook.com>"]
name = "blockchain_peer"
version = "0.1.0"

[dependencies]
r2d2 = "0.7.3"
r2d2_postgres = "0.13.0"
rocket = "0.3.2"
rocket_codegen = "0.3.2"
rocket_contrib = "0.3.2"
rust-crypto = "0.2.36"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"
time = "0.1.38"

[dependencies.postgres]
version = "0.15.1"
features = ["with-uuid"]

[dependencies.uuid]
version = "0.5.1"
features = ["serde"]